# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9a94d788a299652bad0ef562bb6a03f94422c9e3a083842ccc9bdb57416a28860a16dc3830e191bcfde1eff4bfb2cb494c1f0923e8bfae4e29f75ebe96c4d68

test:
  secret_key_base: c08109ef07d8df4aec6b5c988f53bad3505f5d25d478c16245dbc5101d8ba93dae2714201b58a9ec5a5325f92bbe8752f11f7c675869642311dc07f336d8c31d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
